/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Order = IDL.Record({
  'total' : IDL.Nat,
  'items' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
});
export const Product = IDL.Record({ 'name' : IDL.Text, 'price' : IDL.Nat });

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'getOrderHistory' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'placeOrder' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Order = IDL.Record({
    'total' : IDL.Nat,
    'items' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
  });
  const Product = IDL.Record({ 'name' : IDL.Text, 'price' : IDL.Nat });
  
  return IDL.Service({
    'addProduct' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'getOrderHistory' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'placeOrder' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };